// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Tracking.api.despatchbaypro.com {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TrackingServiceBinding", Namespace="urn:despatchbay")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TrackingType))]
    public partial class TrackingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// CodeRemarks
        public TrackingService() {
            this.Url = "http://api.despatchbaypro.com/soap/v11/tracking.php";
        }
        
        public TrackingService(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetTracking", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TrackingType[] GetTracking(string trackingNumber) {
            object[] results = this.Invoke("GetTracking", new object[] {
                        trackingNumber});
            return ((TrackingType[])(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginGetTracking(string trackingNumber, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetTracking", new object[] {
                        trackingNumber}, callback, asyncState);
        }
        
        /// CodeRemarks
        public TrackingType[] EndGetTracking(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((TrackingType[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class TrackingType {
        
        /// <remarks/>
        public string Date;
        
        /// <remarks/>
        public string Time;
        
        /// <remarks/>
        public string Code;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Location;
        
        /// <remarks/>
        public string Signatory;
    }
}
