//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tracking.api.despatchbay.com {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TrackingServiceBinding", Namespace="urn:despatchbay")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TrackingEventType))]
    public partial class TrackingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTrackingOperationCompleted;
        
        /// CodeRemarks
        public TrackingService() {
            this.Url = "http://api.despatchbay.com/soap/v14/tracking.php";
        }
        
        public TrackingService(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event GetTrackingCompletedEventHandler GetTrackingCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetTracking", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public TrackingReturnType GetTracking(string trackingNumber) {
            object[] results = this.Invoke("GetTracking", new object[] {
                        trackingNumber});
            return ((TrackingReturnType)(results[0]));
        }
        
        /// CodeRemarks
        public void GetTrackingAsync(string trackingNumber) {
            this.GetTrackingAsync(trackingNumber, null);
        }
        
        /// CodeRemarks
        public void GetTrackingAsync(string trackingNumber, object userState) {
            if ((this.GetTrackingOperationCompleted == null)) {
                this.GetTrackingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTrackingOperationCompleted);
            }
            this.InvokeAsync("GetTracking", new object[] {
                        trackingNumber}, this.GetTrackingOperationCompleted, userState);
        }
        
        private void OnGetTrackingOperationCompleted(object arg) {
            if ((this.GetTrackingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTrackingCompleted(this, new GetTrackingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class TrackingReturnType {
        
        /// <remarks/>
        public string CourierName;
        
        /// <remarks/>
        public int CourierID;
        
        /// <remarks/>
        public string ServiceName;
        
        /// <remarks/>
        public int ServiceID;
        
        /// <remarks/>
        public string TrackingType;
        
        /// <remarks/>
        public TrackingEventType[] TrackingHistory;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class TrackingEventType {
        
        /// <remarks/>
        public string Date;
        
        /// <remarks/>
        public string Time;
        
        /// <remarks/>
        public string Code;
        
        /// <remarks/>
        public string Description;
        
        /// <remarks/>
        public string Location;
        
        /// <remarks/>
        public string Signatory;
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    public delegate void GetTrackingCompletedEventHandler(object sender, GetTrackingCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTrackingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTrackingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public TrackingReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TrackingReturnType)(this.results[0]));
            }
        }
    }
}
