//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Shipping.com.despatchbay.api {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ShippingServiceBinding", Namespace="urn:despatchbay")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ServiceType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ParcelType))]
    public partial class ShippingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAvailableServicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAvailableCollectionDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddShipmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShipmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCollectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCollectionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelShipmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback BookShipmentsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ShippingService() {
            this.Url = global::Shipping.Properties.Settings.Default.Shipping_com_despatchbay_api_ShippingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetAvailableServicesCompletedEventHandler GetAvailableServicesCompleted;
        
        /// <remarks/>
        public event GetAvailableCollectionDatesCompletedEventHandler GetAvailableCollectionDatesCompleted;
        
        /// <remarks/>
        public event AddShipmentCompletedEventHandler AddShipmentCompleted;
        
        /// <remarks/>
        public event GetShipmentCompletedEventHandler GetShipmentCompleted;
        
        /// <remarks/>
        public event GetCollectionCompletedEventHandler GetCollectionCompleted;
        
        /// <remarks/>
        public event GetCollectionsCompletedEventHandler GetCollectionsCompleted;
        
        /// <remarks/>
        public event CancelShipmentCompletedEventHandler CancelShipmentCompleted;
        
        /// <remarks/>
        public event BookShipmentsCompletedEventHandler BookShipmentsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetAvailableServices", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ServiceType[] GetAvailableServices(ShipmentRequestType Shipment) {
            object[] results = this.Invoke("GetAvailableServices", new object[] {
                        Shipment});
            return ((ServiceType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailableServicesAsync(ShipmentRequestType Shipment) {
            this.GetAvailableServicesAsync(Shipment, null);
        }
        
        /// <remarks/>
        public void GetAvailableServicesAsync(ShipmentRequestType Shipment, object userState) {
            if ((this.GetAvailableServicesOperationCompleted == null)) {
                this.GetAvailableServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailableServicesOperationCompleted);
            }
            this.InvokeAsync("GetAvailableServices", new object[] {
                        Shipment}, this.GetAvailableServicesOperationCompleted, userState);
        }
        
        private void OnGetAvailableServicesOperationCompleted(object arg) {
            if ((this.GetAvailableServicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailableServicesCompleted(this, new GetAvailableServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetAvailableCollectionDates", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public CollectionDateType[] GetAvailableCollectionDates(SenderAddressType SenderAddress, int CourierID) {
            object[] results = this.Invoke("GetAvailableCollectionDates", new object[] {
                        SenderAddress,
                        CourierID});
            return ((CollectionDateType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAvailableCollectionDatesAsync(SenderAddressType SenderAddress, int CourierID) {
            this.GetAvailableCollectionDatesAsync(SenderAddress, CourierID, null);
        }
        
        /// <remarks/>
        public void GetAvailableCollectionDatesAsync(SenderAddressType SenderAddress, int CourierID, object userState) {
            if ((this.GetAvailableCollectionDatesOperationCompleted == null)) {
                this.GetAvailableCollectionDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailableCollectionDatesOperationCompleted);
            }
            this.InvokeAsync("GetAvailableCollectionDates", new object[] {
                        SenderAddress,
                        CourierID}, this.GetAvailableCollectionDatesOperationCompleted, userState);
        }
        
        private void OnGetAvailableCollectionDatesOperationCompleted(object arg) {
            if ((this.GetAvailableCollectionDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailableCollectionDatesCompleted(this, new GetAvailableCollectionDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#AddShipment", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("ShipmentID")]
        public string AddShipment(ShipmentRequestType Shipment) {
            object[] results = this.Invoke("AddShipment", new object[] {
                        Shipment});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddShipmentAsync(ShipmentRequestType Shipment) {
            this.AddShipmentAsync(Shipment, null);
        }
        
        /// <remarks/>
        public void AddShipmentAsync(ShipmentRequestType Shipment, object userState) {
            if ((this.AddShipmentOperationCompleted == null)) {
                this.AddShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddShipmentOperationCompleted);
            }
            this.InvokeAsync("AddShipment", new object[] {
                        Shipment}, this.AddShipmentOperationCompleted, userState);
        }
        
        private void OnAddShipmentOperationCompleted(object arg) {
            if ((this.AddShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddShipmentCompleted(this, new AddShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetShipment", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ShipmentReturnType GetShipment(string ShipmentID) {
            object[] results = this.Invoke("GetShipment", new object[] {
                        ShipmentID});
            return ((ShipmentReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void GetShipmentAsync(string ShipmentID) {
            this.GetShipmentAsync(ShipmentID, null);
        }
        
        /// <remarks/>
        public void GetShipmentAsync(string ShipmentID, object userState) {
            if ((this.GetShipmentOperationCompleted == null)) {
                this.GetShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShipmentOperationCompleted);
            }
            this.InvokeAsync("GetShipment", new object[] {
                        ShipmentID}, this.GetShipmentOperationCompleted, userState);
        }
        
        private void OnGetShipmentOperationCompleted(object arg) {
            if ((this.GetShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShipmentCompleted(this, new GetShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetCollection", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public CollectionReturnType GetCollection(string CollectionID) {
            object[] results = this.Invoke("GetCollection", new object[] {
                        CollectionID});
            return ((CollectionReturnType)(results[0]));
        }
        
        /// <remarks/>
        public void GetCollectionAsync(string CollectionID) {
            this.GetCollectionAsync(CollectionID, null);
        }
        
        /// <remarks/>
        public void GetCollectionAsync(string CollectionID, object userState) {
            if ((this.GetCollectionOperationCompleted == null)) {
                this.GetCollectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCollectionOperationCompleted);
            }
            this.InvokeAsync("GetCollection", new object[] {
                        CollectionID}, this.GetCollectionOperationCompleted, userState);
        }
        
        private void OnGetCollectionOperationCompleted(object arg) {
            if ((this.GetCollectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCollectionCompleted(this, new GetCollectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetCollections", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public CollectionReturnType[] GetCollections() {
            object[] results = this.Invoke("GetCollections", new object[0]);
            return ((CollectionReturnType[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCollectionsAsync() {
            this.GetCollectionsAsync(null);
        }
        
        /// <remarks/>
        public void GetCollectionsAsync(object userState) {
            if ((this.GetCollectionsOperationCompleted == null)) {
                this.GetCollectionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCollectionsOperationCompleted);
            }
            this.InvokeAsync("GetCollections", new object[0], this.GetCollectionsOperationCompleted, userState);
        }
        
        private void OnGetCollectionsOperationCompleted(object arg) {
            if ((this.GetCollectionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCollectionsCompleted(this, new GetCollectionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#CancelShipment", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("Response")]
        public bool CancelShipment(string ShipmentID) {
            object[] results = this.Invoke("CancelShipment", new object[] {
                        ShipmentID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelShipmentAsync(string ShipmentID) {
            this.CancelShipmentAsync(ShipmentID, null);
        }
        
        /// <remarks/>
        public void CancelShipmentAsync(string ShipmentID, object userState) {
            if ((this.CancelShipmentOperationCompleted == null)) {
                this.CancelShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelShipmentOperationCompleted);
            }
            this.InvokeAsync("CancelShipment", new object[] {
                        ShipmentID}, this.CancelShipmentOperationCompleted, userState);
        }
        
        private void OnCancelShipmentOperationCompleted(object arg) {
            if ((this.CancelShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelShipmentCompleted(this, new CancelShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#BookShipments", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ShipmentReturnType[] BookShipments(string[] ShipmentIDs) {
            object[] results = this.Invoke("BookShipments", new object[] {
                        ShipmentIDs});
            return ((ShipmentReturnType[])(results[0]));
        }
        
        /// <remarks/>
        public void BookShipmentsAsync(string[] ShipmentIDs) {
            this.BookShipmentsAsync(ShipmentIDs, null);
        }
        
        /// <remarks/>
        public void BookShipmentsAsync(string[] ShipmentIDs, object userState) {
            if ((this.BookShipmentsOperationCompleted == null)) {
                this.BookShipmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBookShipmentsOperationCompleted);
            }
            this.InvokeAsync("BookShipments", new object[] {
                        ShipmentIDs}, this.BookShipmentsOperationCompleted, userState);
        }
        
        private void OnBookShipmentsOperationCompleted(object arg) {
            if ((this.BookShipmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BookShipmentsCompleted(this, new BookShipmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ShipmentRequestType {
        
        private int serviceIDField;
        
        private bool serviceIDFieldSpecified;
        
        private ParcelType[] parcelsField;
        
        private string clientReferenceField;
        
        private CollectionDateType collectionDateField;
        
        private SenderAddressType senderAddressField;
        
        private RecipientAddressType recipientAddressField;
        
        private bool followShipmentField;
        
        private bool followShipmentFieldSpecified;
        
        /// <remarks/>
        public int ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool ServiceIDSpecified {
            get {
                return this.serviceIDFieldSpecified;
            }
            set {
                this.serviceIDFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public ParcelType[] Parcels {
            get {
                return this.parcelsField;
            }
            set {
                this.parcelsField = value;
            }
        }
        
        /// <remarks/>
        public string ClientReference {
            get {
                return this.clientReferenceField;
            }
            set {
                this.clientReferenceField = value;
            }
        }
        
        /// <remarks/>
        public CollectionDateType CollectionDate {
            get {
                return this.collectionDateField;
            }
            set {
                this.collectionDateField = value;
            }
        }
        
        /// <remarks/>
        public SenderAddressType SenderAddress {
            get {
                return this.senderAddressField;
            }
            set {
                this.senderAddressField = value;
            }
        }
        
        /// <remarks/>
        public RecipientAddressType RecipientAddress {
            get {
                return this.recipientAddressField;
            }
            set {
                this.recipientAddressField = value;
            }
        }
        
        /// <remarks/>
        public bool FollowShipment {
            get {
                return this.followShipmentField;
            }
            set {
                this.followShipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool FollowShipmentSpecified {
            get {
                return this.followShipmentFieldSpecified;
            }
            set {
                this.followShipmentFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ParcelType {
        
        private float weightField;
        
        private float lengthField;
        
        private float widthField;
        
        private float heightField;
        
        private string contentsField;
        
        private float valueField;
        
        private bool valueFieldSpecified;
        
        private string trackingNumberField;
        
        /// <remarks/>
        public float Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
            }
        }
        
        /// <remarks/>
        public float Length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
            }
        }
        
        /// <remarks/>
        public float Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
            }
        }
        
        /// <remarks/>
        public float Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
            }
        }
        
        /// <remarks/>
        public string Contents {
            get {
                return this.contentsField;
            }
            set {
                this.contentsField = value;
            }
        }
        
        /// <remarks/>
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class CollectionReturnType {
        
        private string collectionIDField;
        
        private string collectionDocumentIDField;
        
        private string collectionTypeField;
        
        private CollectionDateType collectionDateField;
        
        private SenderAddressType senderAddressField;
        
        private CourierType courierField;
        
        private string labelsURLField;
        
        private string manifestURLField;
        
        /// <remarks/>
        public string CollectionID {
            get {
                return this.collectionIDField;
            }
            set {
                this.collectionIDField = value;
            }
        }
        
        /// <remarks/>
        public string CollectionDocumentID {
            get {
                return this.collectionDocumentIDField;
            }
            set {
                this.collectionDocumentIDField = value;
            }
        }
        
        /// <remarks/>
        public string CollectionType {
            get {
                return this.collectionTypeField;
            }
            set {
                this.collectionTypeField = value;
            }
        }
        
        /// <remarks/>
        public CollectionDateType CollectionDate {
            get {
                return this.collectionDateField;
            }
            set {
                this.collectionDateField = value;
            }
        }
        
        /// <remarks/>
        public SenderAddressType SenderAddress {
            get {
                return this.senderAddressField;
            }
            set {
                this.senderAddressField = value;
            }
        }
        
        /// <remarks/>
        public CourierType Courier {
            get {
                return this.courierField;
            }
            set {
                this.courierField = value;
            }
        }
        
        /// <remarks/>
        public string LabelsURL {
            get {
                return this.labelsURLField;
            }
            set {
                this.labelsURLField = value;
            }
        }
        
        /// <remarks/>
        public string ManifestURL {
            get {
                return this.manifestURLField;
            }
            set {
                this.manifestURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class CollectionDateType {
        
        private string collectionDateField;
        
        /// <remarks/>
        public string CollectionDate {
            get {
                return this.collectionDateField;
            }
            set {
                this.collectionDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class SenderAddressType {
        
        private string senderNameField;
        
        private string senderTelephoneField;
        
        private string senderEmailField;
        
        private AddressType senderAddressField;
        
        private int senderAddressIDField;
        
        private bool senderAddressIDFieldSpecified;
        
        /// <remarks/>
        public string SenderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
            }
        }
        
        /// <remarks/>
        public string SenderTelephone {
            get {
                return this.senderTelephoneField;
            }
            set {
                this.senderTelephoneField = value;
            }
        }
        
        /// <remarks/>
        public string SenderEmail {
            get {
                return this.senderEmailField;
            }
            set {
                this.senderEmailField = value;
            }
        }
        
        /// <remarks/>
        public AddressType SenderAddress {
            get {
                return this.senderAddressField;
            }
            set {
                this.senderAddressField = value;
            }
        }
        
        /// <remarks/>
        public int SenderAddressID {
            get {
                return this.senderAddressIDField;
            }
            set {
                this.senderAddressIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool SenderAddressIDSpecified {
            get {
                return this.senderAddressIDFieldSpecified;
            }
            set {
                this.senderAddressIDFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class AddressType {
        
        private string companyNameField;
        
        private string streetField;
        
        private string localityField;
        
        private string townCityField;
        
        private string countyField;
        
        private string postalCodeField;
        
        private string countryCodeField;
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
            }
        }
        
        /// <remarks/>
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <remarks/>
        public string TownCity {
            get {
                return this.townCityField;
            }
            set {
                this.townCityField = value;
            }
        }
        
        /// <remarks/>
        public string County {
            get {
                return this.countyField;
            }
            set {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class CourierType {
        
        private string courierIDField;
        
        private string courierNameField;
        
        /// <remarks/>
        public string CourierID {
            get {
                return this.courierIDField;
            }
            set {
                this.courierIDField = value;
            }
        }
        
        /// <remarks/>
        public string CourierName {
            get {
                return this.courierNameField;
            }
            set {
                this.courierNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ShipmentReturnType {
        
        private string shipmentIDField;
        
        private string shipmentDocumentIDField;
        
        private string collectionIDField;
        
        private string collectionDocumentIDField;
        
        private int serviceIDField;
        
        private ParcelType[] parcelsField;
        
        private string clientReferenceField;
        
        private RecipientAddressType recipientAddressField;
        
        private bool isFollowedField;
        
        private bool isFollowedFieldSpecified;
        
        private bool isDespatchedField;
        
        private bool isPrintedField;
        
        private bool isDeliveredField;
        
        private bool isCancelledField;
        
        private string labelsURLField;
        
        /// <remarks/>
        public string ShipmentID {
            get {
                return this.shipmentIDField;
            }
            set {
                this.shipmentIDField = value;
            }
        }
        
        /// <remarks/>
        public string ShipmentDocumentID {
            get {
                return this.shipmentDocumentIDField;
            }
            set {
                this.shipmentDocumentIDField = value;
            }
        }
        
        /// <remarks/>
        public string CollectionID {
            get {
                return this.collectionIDField;
            }
            set {
                this.collectionIDField = value;
            }
        }
        
        /// <remarks/>
        public string CollectionDocumentID {
            get {
                return this.collectionDocumentIDField;
            }
            set {
                this.collectionDocumentIDField = value;
            }
        }
        
        /// <remarks/>
        public int ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
            }
        }
        
        /// <remarks/>
        public ParcelType[] Parcels {
            get {
                return this.parcelsField;
            }
            set {
                this.parcelsField = value;
            }
        }
        
        /// <remarks/>
        public string ClientReference {
            get {
                return this.clientReferenceField;
            }
            set {
                this.clientReferenceField = value;
            }
        }
        
        /// <remarks/>
        public RecipientAddressType RecipientAddress {
            get {
                return this.recipientAddressField;
            }
            set {
                this.recipientAddressField = value;
            }
        }
        
        /// <remarks/>
        public bool IsFollowed {
            get {
                return this.isFollowedField;
            }
            set {
                this.isFollowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsFollowedSpecified {
            get {
                return this.isFollowedFieldSpecified;
            }
            set {
                this.isFollowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsDespatched {
            get {
                return this.isDespatchedField;
            }
            set {
                this.isDespatchedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsPrinted {
            get {
                return this.isPrintedField;
            }
            set {
                this.isPrintedField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDelivered {
            get {
                return this.isDeliveredField;
            }
            set {
                this.isDeliveredField = value;
            }
        }
        
        /// <remarks/>
        public bool IsCancelled {
            get {
                return this.isCancelledField;
            }
            set {
                this.isCancelledField = value;
            }
        }
        
        /// <remarks/>
        public string LabelsURL {
            get {
                return this.labelsURLField;
            }
            set {
                this.labelsURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class RecipientAddressType {
        
        private string recipientNameField;
        
        private string recipientTelephoneField;
        
        private string recipientEmailField;
        
        private AddressType recipientAddressField;
        
        /// <remarks/>
        public string RecipientName {
            get {
                return this.recipientNameField;
            }
            set {
                this.recipientNameField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientTelephone {
            get {
                return this.recipientTelephoneField;
            }
            set {
                this.recipientTelephoneField = value;
            }
        }
        
        /// <remarks/>
        public string RecipientEmail {
            get {
                return this.recipientEmailField;
            }
            set {
                this.recipientEmailField = value;
            }
        }
        
        /// <remarks/>
        public AddressType RecipientAddress {
            get {
                return this.recipientAddressField;
            }
            set {
                this.recipientAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ServiceType {
        
        private int serviceIDField;
        
        private string formatField;
        
        private string nameField;
        
        private float costField;
        
        private bool costFieldSpecified;
        
        private CourierType courierField;
        
        /// <remarks/>
        public int ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
            }
        }
        
        /// <remarks/>
        public string Format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public float Cost {
            get {
                return this.costField;
            }
            set {
                this.costField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool CostSpecified {
            get {
                return this.costFieldSpecified;
            }
            set {
                this.costFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public CourierType Courier {
            get {
                return this.courierField;
            }
            set {
                this.courierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAvailableServicesCompletedEventHandler(object sender, GetAvailableServicesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailableServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailableServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ServiceType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetAvailableCollectionDatesCompletedEventHandler(object sender, GetAvailableCollectionDatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailableCollectionDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailableCollectionDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CollectionDateType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CollectionDateType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AddShipmentCompletedEventHandler(object sender, AddShipmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetShipmentCompletedEventHandler(object sender, GetShipmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ShipmentReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ShipmentReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetCollectionCompletedEventHandler(object sender, GetCollectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCollectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCollectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CollectionReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CollectionReturnType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void GetCollectionsCompletedEventHandler(object sender, GetCollectionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCollectionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCollectionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CollectionReturnType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CollectionReturnType[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void CancelShipmentCompletedEventHandler(object sender, CancelShipmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void BookShipmentsCompletedEventHandler(object sender, BookShipmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BookShipmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BookShipmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ShipmentReturnType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ShipmentReturnType[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591