//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping.api.despatchbay.com {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ShippingServiceBinding", Namespace="urn:despatchbay")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ServiceType))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(ParcelType))]
    public partial class ShippingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetAvailableServicesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAvailableCollectionDatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddShipmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetShipmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelShipmentOperationCompleted;
        
        /// CodeRemarks
        public ShippingService() {
            this.Url = "http://api.despatchbay.com/soap/v14/shipping.php";
        }
        
        public ShippingService(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        public event GetAvailableServicesCompletedEventHandler GetAvailableServicesCompleted;
        
        /// CodeRemarks
        public event GetAvailableCollectionDatesCompletedEventHandler GetAvailableCollectionDatesCompleted;
        
        /// CodeRemarks
        public event AddShipmentCompletedEventHandler AddShipmentCompleted;
        
        /// CodeRemarks
        public event GetShipmentCompletedEventHandler GetShipmentCompleted;
        
        /// CodeRemarks
        public event CancelShipmentCompletedEventHandler CancelShipmentCompleted;
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetAvailableServices", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ServiceType[] GetAvailableServices(ShipmentRequestType Shipment) {
            object[] results = this.Invoke("GetAvailableServices", new object[] {
                        Shipment});
            return ((ServiceType[])(results[0]));
        }
        
        /// CodeRemarks
        public void GetAvailableServicesAsync(ShipmentRequestType Shipment) {
            this.GetAvailableServicesAsync(Shipment, null);
        }
        
        /// CodeRemarks
        public void GetAvailableServicesAsync(ShipmentRequestType Shipment, object userState) {
            if ((this.GetAvailableServicesOperationCompleted == null)) {
                this.GetAvailableServicesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailableServicesOperationCompleted);
            }
            this.InvokeAsync("GetAvailableServices", new object[] {
                        Shipment}, this.GetAvailableServicesOperationCompleted, userState);
        }
        
        private void OnGetAvailableServicesOperationCompleted(object arg) {
            if ((this.GetAvailableServicesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailableServicesCompleted(this, new GetAvailableServicesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetAvailableCollectionDates", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public CollectionDateType[] GetAvailableCollectionDates(SenderAddressType SenderAddress, int CourierID) {
            object[] results = this.Invoke("GetAvailableCollectionDates", new object[] {
                        SenderAddress,
                        CourierID});
            return ((CollectionDateType[])(results[0]));
        }
        
        /// CodeRemarks
        public void GetAvailableCollectionDatesAsync(SenderAddressType SenderAddress, int CourierID) {
            this.GetAvailableCollectionDatesAsync(SenderAddress, CourierID, null);
        }
        
        /// CodeRemarks
        public void GetAvailableCollectionDatesAsync(SenderAddressType SenderAddress, int CourierID, object userState) {
            if ((this.GetAvailableCollectionDatesOperationCompleted == null)) {
                this.GetAvailableCollectionDatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAvailableCollectionDatesOperationCompleted);
            }
            this.InvokeAsync("GetAvailableCollectionDates", new object[] {
                        SenderAddress,
                        CourierID}, this.GetAvailableCollectionDatesOperationCompleted, userState);
        }
        
        private void OnGetAvailableCollectionDatesOperationCompleted(object arg) {
            if ((this.GetAvailableCollectionDatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAvailableCollectionDatesCompleted(this, new GetAvailableCollectionDatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#AddShipment", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("ShipmentID")]
        public string AddShipment(ShipmentRequestType Shipment) {
            object[] results = this.Invoke("AddShipment", new object[] {
                        Shipment});
            return ((string)(results[0]));
        }
        
        /// CodeRemarks
        public void AddShipmentAsync(ShipmentRequestType Shipment) {
            this.AddShipmentAsync(Shipment, null);
        }
        
        /// CodeRemarks
        public void AddShipmentAsync(ShipmentRequestType Shipment, object userState) {
            if ((this.AddShipmentOperationCompleted == null)) {
                this.AddShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddShipmentOperationCompleted);
            }
            this.InvokeAsync("AddShipment", new object[] {
                        Shipment}, this.AddShipmentOperationCompleted, userState);
        }
        
        private void OnAddShipmentOperationCompleted(object arg) {
            if ((this.AddShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddShipmentCompleted(this, new AddShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetShipment", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public ShipmentReturnType GetShipment(string ShipmentID) {
            object[] results = this.Invoke("GetShipment", new object[] {
                        ShipmentID});
            return ((ShipmentReturnType)(results[0]));
        }
        
        /// CodeRemarks
        public void GetShipmentAsync(string ShipmentID) {
            this.GetShipmentAsync(ShipmentID, null);
        }
        
        /// CodeRemarks
        public void GetShipmentAsync(string ShipmentID, object userState) {
            if ((this.GetShipmentOperationCompleted == null)) {
                this.GetShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetShipmentOperationCompleted);
            }
            this.InvokeAsync("GetShipment", new object[] {
                        ShipmentID}, this.GetShipmentOperationCompleted, userState);
        }
        
        private void OnGetShipmentOperationCompleted(object arg) {
            if ((this.GetShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetShipmentCompleted(this, new GetShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#CancelShipment", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("Response")]
        public bool CancelShipment(string ShipmentID) {
            object[] results = this.Invoke("CancelShipment", new object[] {
                        ShipmentID});
            return ((bool)(results[0]));
        }
        
        /// CodeRemarks
        public void CancelShipmentAsync(string ShipmentID) {
            this.CancelShipmentAsync(ShipmentID, null);
        }
        
        /// CodeRemarks
        public void CancelShipmentAsync(string ShipmentID, object userState) {
            if ((this.CancelShipmentOperationCompleted == null)) {
                this.CancelShipmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelShipmentOperationCompleted);
            }
            this.InvokeAsync("CancelShipment", new object[] {
                        ShipmentID}, this.CancelShipmentOperationCompleted, userState);
        }
        
        private void OnCancelShipmentOperationCompleted(object arg) {
            if ((this.CancelShipmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelShipmentCompleted(this, new CancelShipmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// CodeRemarks
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ShipmentRequestType {
        
        /// <remarks/>
        public int ServiceID;
        
        /// <remarks/>
        public ParcelType[] Parcels;
        
        /// <remarks/>
        public string ClientReference;
        
        /// <remarks/>
        public CollectionDateType CollectionDate;
        
        /// <remarks/>
        public SenderAddressType SenderAddress;
        
        /// <remarks/>
        public RecipientAddressType RecipientAddress;
        
        /// <remarks/>
        public bool FollowShipment;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool FollowShipmentSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ParcelType {
        
        /// <remarks/>
        public float Weight;
        
        /// <remarks/>
        public float Length;
        
        /// <remarks/>
        public float Width;
        
        /// <remarks/>
        public float Height;
        
        /// <remarks/>
        public string Contents;
        
        /// <remarks/>
        public float Value;
        
        /// <remarks/>
        public string TrackingNumber;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ShipmentReturnType {
        
        /// <remarks/>
        public string ShipmentID;
        
        /// <remarks/>
        public int ServiceID;
        
        /// <remarks/>
        public ParcelType[] Parcels;
        
        /// <remarks/>
        public string ClientReference;
        
        /// <remarks/>
        public RecipientAddressType RecipientAddress;
        
        /// <remarks/>
        public bool IsFollowed;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool IsFollowedSpecified;
        
        /// <remarks/>
        public bool IsDespatched;
        
        /// <remarks/>
        public bool IsPrinted;
        
        /// <remarks/>
        public bool IsDelivered;
        
        /// <remarks/>
        public bool IsCancelled;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class RecipientAddressType {
        
        /// <remarks/>
        public string RecipientName;
        
        /// <remarks/>
        public string RecipientTelephone;
        
        /// <remarks/>
        public string RecipientEmail;
        
        /// <remarks/>
        public AddressType RecipientAddress;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class AddressType {
        
        /// <remarks/>
        public string CompanyName;
        
        /// <remarks/>
        public string Street;
        
        /// <remarks/>
        public string Locality;
        
        /// <remarks/>
        public string TownCity;
        
        /// <remarks/>
        public string County;
        
        /// <remarks/>
        public string PostalCode;
        
        /// <remarks/>
        public string CountryCode;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class CourierType {
        
        /// <remarks/>
        public string CourierID;
        
        /// <remarks/>
        public string CourierName;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class ServiceType {
        
        /// <remarks/>
        public int ServiceID;
        
        /// <remarks/>
        public string Name;
        
        /// <remarks/>
        public float Cost;
        
        /// <remarks/>
        public CourierType Courier;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class SenderAddressType {
        
        /// <remarks/>
        public string SenderName;
        
        /// <remarks/>
        public string SenderTelephone;
        
        /// <remarks/>
        public string SenderEmail;
        
        /// <remarks/>
        public AddressType SenderAddress;
        
        /// <remarks/>
        public int SenderAddressID;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool SenderAddressIDSpecified;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class CollectionDateType {
        
        /// <remarks/>
        public string CollectionDate;
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    public delegate void GetAvailableServicesCompletedEventHandler(object sender, GetAvailableServicesCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailableServicesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailableServicesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ServiceType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ServiceType[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    public delegate void GetAvailableCollectionDatesCompletedEventHandler(object sender, GetAvailableCollectionDatesCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAvailableCollectionDatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAvailableCollectionDatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public CollectionDateType[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CollectionDateType[])(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    public delegate void AddShipmentCompletedEventHandler(object sender, AddShipmentCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    public delegate void GetShipmentCompletedEventHandler(object sender, GetShipmentCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public ShipmentReturnType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ShipmentReturnType)(this.results[0]));
            }
        }
    }
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    public delegate void CancelShipmentCompletedEventHandler(object sender, CancelShipmentCompletedEventArgs e);
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "7.4.0.1033")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelShipmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelShipmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// CodeRemarks
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}
