// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Addressing.api.despatchbaypro.com {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// CodeRemarks
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AddressingServiceBinding", Namespace="urn:despatchbay")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AddressKeyType))]
    public partial class AddressingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// CodeRemarks
        public AddressingService() {
            this.Url = "http://api.despatchbaypro.com/soap/v11/addressing.php";
        }
        
        public AddressingService(string url) {
            this.Url = url;
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetDomesticAddressByLookup", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AddressDetailType GetDomesticAddressByLookup(string postcode, string property) {
            object[] results = this.Invoke("GetDomesticAddressByLookup", new object[] {
                        postcode,
                        property});
            return ((AddressDetailType)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginGetDomesticAddressByLookup(string postcode, string property, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDomesticAddressByLookup", new object[] {
                        postcode,
                        property}, callback, asyncState);
        }
        
        /// CodeRemarks
        public AddressDetailType EndGetDomesticAddressByLookup(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AddressDetailType)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetDomesticAddressByKey", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AddressDetailType GetDomesticAddressByKey(string key) {
            object[] results = this.Invoke("GetDomesticAddressByKey", new object[] {
                        key});
            return ((AddressDetailType)(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginGetDomesticAddressByKey(string key, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDomesticAddressByKey", new object[] {
                        key}, callback, asyncState);
        }
        
        /// CodeRemarks
        public AddressDetailType EndGetDomesticAddressByKey(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AddressDetailType)(results[0]));
        }
        
        /// CodeRemarks
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:despatchbay#GetDomesticAddressKeysByPostcode", RequestNamespace="urn:despatchbay", ResponseNamespace="urn:despatchbay")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public AddressKeyType[] GetDomesticAddressKeysByPostcode(string postcode) {
            object[] results = this.Invoke("GetDomesticAddressKeysByPostcode", new object[] {
                        postcode});
            return ((AddressKeyType[])(results[0]));
        }
        
        /// CodeRemarks
        public System.IAsyncResult BeginGetDomesticAddressKeysByPostcode(string postcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GetDomesticAddressKeysByPostcode", new object[] {
                        postcode}, callback, asyncState);
        }
        
        /// CodeRemarks
        public AddressKeyType[] EndGetDomesticAddressKeysByPostcode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AddressKeyType[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class AddressDetailType {
        
        /// <remarks/>
        public string CompanyName;
        
        /// <remarks/>
        public string Street;
        
        /// <remarks/>
        public string Locality;
        
        /// <remarks/>
        public string Town;
        
        /// <remarks/>
        public string County;
        
        /// <remarks/>
        public string Country;
        
        /// <remarks/>
        public string Postcode;
        
        /// <remarks/>
        public string Key;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:despatchbay")]
    public partial class AddressKeyType {
        
        /// <remarks/>
        public string Key;
        
        /// <remarks/>
        public string Address;
    }
}
